name: Lobby-Parkour
version: '1.0.0'
main: net.crumb.lobbyParkour.LobbyParkour
description: A plugin that adds an easy controllable lobby parkour
api-version: '1.21'
author: crumb
folia-supported: true
softdepend: ["PlaceholderAPI"]
commands:
  lpk:
    description: Main command
    usage: /lpk <args>
    aliases: lobby-parkour

permissions:
  lpk.admin:
    description: Allows a player to access all /lpk <args> commands
    default: op
